[[session]]
name = "ğŸ  Home"
path = "~"

[[session]]
name = "ğŸ—’ï¸ Scratch"
path = "~/Scratch"
startup_command = "c && lsa"

[[session]]
name = "ğŸ› ï¸ Dotfiles"
path = "~/.dotfiles"
# startup_command = "v . '+Telescope find_files hidden=true'; clear"
startup_command = "c && lsa && gs"

[[session]]
# TODO Change Hyprland session to "\e[38;2;35;88;100mï™\e[0m Hyprland"
name = "ï™ Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "v hyprland.conf;c"

[[session]]
name = "îš® NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "v . '+Telescope find_files';c"

[[session]]
name = "î˜² Emacs"
path = "~/.dotfiles/.doom.d"
startup_command = "v config.el;c"

[[session]]
name = "âŒ¨ï¸ Kanata"
path = "~/.dotfiles/kanata"
startup_command = "v kanata.kbd;c"

[[session]]
# TODO: Change Waybar session to "\e[38;2;255;190;8mï§\e[0m Waybar"
name = "ï§ Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "v config.jsonc;c"

[[session]]
name = "ğŸ” Rofi"
path = "~/.dotfiles/.config/rofi"
startup_command = "v config.rasi;c"

[[session]]
# TODO: Fix î¯ˆ not working
name = "ğŸªŸ Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "v sesh.toml;c"

[[session]]
name = "âš™ï¸ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "v .;c"

[[session]]
name = "ğŸ¦ Vault"
path = "~/Vault"
startup_command = "vault;c"

[[session]]
name = "ğŸ““ Notes"
path = "~/Vault/notes"
startup_command = "c && lst"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“„ Documents"
path = "~/Documents"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“¹ Videos"
path = "~/Videos"
startup_command = "c && lsa"

[[session]]
name = "ğŸµ Music"
path = "~/Music"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“¸ Pictures"
path = "~/Pictures"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“š Library"
path = "~/Documents/Library"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“– Dictionary"
path = "/home/allisnull/.config/nvim/spell"
startup_command = "v .;c"

[[session]]
name = "ó°• Zsh-Undo-Dir"
path = "~/.dotfiles/.zsh/plugins/zsh-undo-dir"
startup_command = "v zsh-undo-dir.plugin.zsh;c"

[[session]]
name = "ğŸ§  Brain"
path = "~/Programming/work/flutter/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "ğŸª¹ Birds Nest"
path = "~/Programming/work/flutter/BirdsNest/birds_nest"
startup_command = "~/.config/sesh/scripts/flutter.sh"
