[default_sessiono]
startup_command = "clear && tree -dL 3 && eza -a --icons=always"

[[session]]
name = "ğŸ  Main"
path = "~"

[[session]]
name = "ğŸ—’ï¸ Scratch"
path = "~/Scratch"
disable_startup_command = true

[[session]]
name = "ğŸ› ï¸ Dotfiles"
path = "~/.dotfiles"
startup_command = "nvim . '+Telescope find_files hidden=true'; clear"

[[session]]
name = "îš® NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim . '+Telescope find_files'; clear"

[[session]]
name = "âš™ï¸ Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml; clear"

[[session]]
name = "ğŸ” Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "nvim config.jsonc; clear"

[[session]]
name = "ğŸªŸ Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "nvim hyprland.conf; clear"

[[session]]
name = "âš™ï¸ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "nvim .; clear"

[[session]]
name = "ğŸ““ Notes"
path = "~/Notes"

[[session]]
name = "ğŸ§  Brain"
path = "~/Programming/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/brain.sh"

[[session]]
name = "ğŸ“– Dictionary"
path = "/home/allisnull/.cache/nvim/ltex"
startup_command = "nvim en-US.txt; clear"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"

[[session]]
name = "ğŸ“„ Documents"
path = "~/Documents"

[[session]]
name = "ğŸ“¹ Videos"
path = "~/Videos"

[[session]]
name = "ğŸµ Music"
path = "~/Music"

[[session]]
name = "ğŸ“¸ Pictures"
path = "~/Pictures"
