[[session]]
name = "ğŸ  Home"
path = "~"
startup_command = "clear && fastfetch"

[[session]]
name = "ğŸ—’ï¸ Scratch"
path = "~/Scratch"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ› ï¸ Dotfiles"
path = "~/.dotfiles"
# startup_command = "nvim . '+Telescope find_files hidden=true'; clear"
startup_command = "clear && eza -a --icons=always && git status"

[[session]]
# TODO Change Hyprland session to "\e[38;2;35;88;100mï™\e[0m Hyprland"
name = "ï™ Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "nvim hyprland.conf; clear"

[[session]]
name = "îš® NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim . '+Telescope find_files'; clear"

[[session]]
name = "î˜² Emacs"
path = "~/.dotfiles/.doom.d"
startup_command = "nvim config.el; clear"

[[session]]
name = "âŒ¨ï¸ Kanata"
path = "~/.dotfiles/kanata"
startup_command = "nvim kanata.kdb; clear"

[[session]]
# TODO: Change Waybar session to "\e[38;2;255;190;8mï§\e[0m Waybar"
name = "ï§ Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "nvim config.jsonc; clear"

[[session]]
name = "ğŸ” Rofi"
path = "~/.dotfiles/.config/rofi"
startup_command = "nvim config.rasi; clear"

[[session]]
# TODO: Fix î¯ˆ not working
name = "î¯ˆ Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml; clear"

[[session]]
name = "âš™ï¸ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "nvim .; clear"

[[session]]
name = "ğŸ¦ Vault"
path = "~/Vault"
startup_command = "nvim 1741211101-main-hub.md '+ObsidianQuickSwitch'; clear"

[[session]]
name = "ğŸ““ Notes"
path = "~/Vault/notes"
startup_command = "clear && eza --tree --icons=always"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“„ Documents"
path = "~/Documents"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“¹ Videos"
path = "~/Videos"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸµ Music"
path = "~/Music"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“¸ Pictures"
path = "~/Pictures"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“– Dictionary"
path = "/home/allisnull/.config/nvim/spell"
startup_command = "nvim .; clear"

[[session]]
name = "ğŸ“š Library"
path = "~/Documents/Library"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ§  Brain"
path = "~/Programming/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "ğŸª¹ Birds Nest"
path = "~/Programming/BirdsNest/birds_nest"
startup_command = "~/.config/sesh/scripts/flutter.sh"
