[[session]]
name = "ğŸ  Main"
path = "~"
startup_command = "clear && fastfetch"

[[session]]
name = "ğŸ—’ï¸ Scratch"
path = "~/Scratch"

[[session]]
name = "ğŸ› ï¸ Dotfiles"
path = "~/.dotfiles"
# startup_command = "nvim . '+Telescope find_files hidden=true'; clear"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "îš® NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim . '+Telescope find_files'; clear"

[[session]]
name = "âš™ï¸ Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml; clear"

[[session]]
name = "âŒ¨ï¸ Kanata"
path = "~/.dotfiles/kanata"
startup_command = "nvim kanata.kdb; clear"

[[session]]
name = "ğŸ” Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "nvim config.jsonc; clear"

[[session]]
name = "ğŸªŸ Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "nvim hyprland.conf; clear"

[[session]]
name = "âš™ï¸ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "nvim .; clear"

[[session]]
name = "ğŸ¦ Vault"
path = "~/Vault"

[[session]]
name = "ğŸ““ Notes"
path = "~/Notes"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ§  Brain"
path = "~/Programming/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/brain.sh"

[[session]]
name = "ğŸ“– Dictionary"
path = "/home/allisnull/.cache/nvim/ltex"
startup_command = "nvim en-US.txt; clear"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“„ Documents"
path = "~/Documents"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“¹ Videos"
path = "~/Videos"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸµ Music"
path = "~/Music"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "ğŸ“¸ Pictures"
path = "~/Pictures"
startup_command = "clear && eza -a --icons=always"
