[[session]]
name = "ğŸ  Home"
path = "~"

[[session]]
name = "ğŸ—’ï¸ Scratch"
path = "~/Scratch"
startup_command = "c && lsa"

[[session]]
name = "ğŸ› ï¸ Dotfiles"
path = "~/.dotfiles"
# startup_command = "v . '+Telescope find_files hidden=true'; clear"
startup_command = "c && lsa && gs"

[[session]]
name = "#[fg=#56bce1]ï™#[fg=#000000] Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "v hyprland.conf;c"

[[session]]
name = "#[fg=#83b06c]îš®#[fg=#000000] NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "v . '+Telescope find_files';c"

[[session]]
name = "#[fg=#83b06c]îš®#[fg=#000000] NvimPager"
path = "~/.dotfiles/.config/nvimpager"
startup_command = "v init.lua '+AutoSession restore';c"

[[session]]
name = "#[fg=#7c65b4]î˜²#[fg=#000000] Emacs"
path = "~/.dotfiles/.emacs.legacy"
startup_command = "v init.el;c"

[[session]]
name = "âŒ¨ï¸ Kanata"
path = "~/.dotfiles/kanata"
startup_command = "v kanata.kbd;c"

[[session]]
name = "#[fg=#f6be41]ï§#[fg=#000000] Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "v config.jsonc;c"

[[session]]
name = "ğŸ” Rofi"
path = "~/.dotfiles/.config/rofi"
startup_command = "v config.rasi;c"

[[session]]
# TODO: Fix î¯ˆ not working
name = "ğŸªŸ Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "v sesh.toml;c"

[[session]]
name = "âš™ï¸ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "v .;c"

[[session]]
name = "ğŸ¦ Vault"
path = "~/Vault"
startup_command = "vault;c"

[[session]]
name = "ğŸ““ Notes"
path = "~/Vault/notes"
startup_command = "c && lst"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“„ Documents"
path = "~/Documents"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“¹ Videos"
path = "~/Videos"
startup_command = "y;c"

[[session]]
name = "ğŸµ Music"
path = "~/Music"
startup_command = "c && lsa"

[[session]]
name = "ğŸ“¸ Pictures"
path = "~/Pictures"
startup_command = "y;c"

[[session]]
name = "ğŸ“š Library"
path = "~/Documents/Library"
startup_command = "y;c"

[[session]]
name = "#[fg=#4000c0]îº¾#[fg=#000000] Documentation"
path = "/usr/share/doc"
startup_command = "y;c"

[[session]]
name = "ğŸ“– Dictionary"
path = "/home/allisnull/.config/nvim/spell"
startup_command = "v .;c"

[[session]]
name = "ğŸ”§ Settings"
path = "~/Documents/Settings"
startup_command = "c && lsa"

# Projects
[[session]]
name = "#[fg=#660606]ó°•#[fg=#000000] Zsh-Undo-Dir"
path = "~/.dotfiles/.zsh/plugins/zsh-undo-dir"
startup_command = "v zsh-undo-dir.plugin.zsh;c"

[[session]]
name = "ğŸ§  Brain"
path = "~/Programming/work/flutter/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "ğŸª¹ Birds Nest"
path = "~/Programming/work/flutter/BirdsNest/birds_nest"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "ğŸ§‘ğŸ½â€ğŸŒ¾ TheFarmerWasReplaced"
path = "~/.steam/steam/steamapps/compatdata/2060160/pfx/drive_c/users/steamuser/AppData/LocalLow/TheFarmerWasReplaced/TheFarmerWasReplaced/Saves/TheFarmerWasReplaced"
startup_command = "v main.py '+lua vim.diagnostic.enable(false)' '+Telescope find_files';c"
